### ISSUE TITLE
Change card image format to 840x1300

### ISSUE THREAD

**Issue by nlsui** [DecentralCardGame/Cardchain#111]
Unity can only compress images with image sizes that can be split by 4.
Right no we have 838x1300 and 838 makes compressing not possible.
Pls change all existing card images to 840x1300 and make sure alle future card images have that format.

**Comment by patrickwieth** [comment]
Currently the blockchain has no format limitations, but if we want to enforce this, we should do it on the blockchain and the. Frontend follows

**Comment by patrickwieth** [comment]
This has been considered as not optimal, because gas prices would increase a lot and are already very high for uploading artwork. We are favoring a solution, where the council works as a check here:
The blockchain accepts all formats, only checks the file size and limits it. The council however does not display artwork of incorrect format and thus council members should reject the card.

**Comment by nlsui** [comment]
ok, i guess the frontend change will do it for now
