### ISSUE TITLE
Request for starter cards

### ISSUE THREAD

**Issue by lxgr-linux** [DecentralCardGame/Cardchain#154]
calculate avilable cards in client by owned cards + starterdecks

**Comment by lxgr-linux** [comment]
@nlsui Startercards are added to new players cards directly, when users are created.
We might update the migrate script, so every user gets the startercards at migration

**Comment by lxgr-linux** [comment]
No they can't, that would destroy their purpose.

**Comment by patrickwieth** [comment]
Wait a second. Didn't we plan to **not** add the Starter Cards to the user entry?

**Comment by lxgr-linux** [comment]
Did we? It was implemented like it anyways.

**Comment by patrickwieth** [comment]
We discussed this not long ago, maybe 2 or 3 weeks?

The idea was to have a route that gives all starter cards. We did not want to add it to the user owned cards list, because they are not traded and are the same entries for all players and have no use there.

But if we did it anyway like that, fine

**Comment by lxgr-linux** [comment]
Was I involved in that discussion? Because I can't recall.

**Comment by patrickwieth** [comment]
I think yes, that thing ended up in the route that gives you all the StarterCards https://github.com/DecentralCardGame/Cardchain/issues/135
you already implemented it according to how we specified it?

**Comment by lxgr-linux** [comment]
Yes, startercards can be queried via q-cards
