### ISSUE TITLE
query non-existent set gives strange result

### ISSUE THREAD

**Issue by patrickwieth** [DecentralCardGame/Cardchain#158]
querying a set-id that does not exist should result in a response that index is out of range or set id does not exist. Currently some empty set with a strange and big artwork is returned..

**Comment by patrickwieth** [comment]
@lxgr-linux I think you fixed this, right?

**Comment by lxgr-linux** [comment]
This is expected to happen, since this is the default initialisation of a struct. The artwork  comes, because this is the artwork with the id 0 which is the default for the artwork id in the set struct.

Since you don't just randomly query sets, and since the name and everything will be empty it really does not matter.
